baseURL = "/"
title = "Maja Kokot"
theme = "academic"

[markup]
  [markup.goldmark.renderer]
    # This allows KaTeX to work by letting it use raw HTML
    unsafe = true
  [markup.highlight]
    # This enables code syntax highlighting
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    # Pick a style here: https://xyproto.github.io/splash/docs/all.html
    style = "dracula"
    tabWidth = 4

[params]
  # For the header nav bar
  name = "Maja Kokot"

  # --- Main Navigation Links ---
  [[params.links]]
    name = "Home"
    url = "/#about"
  [[params.links]]
    name = "Writing"
    url = "/#writing"
  [[params.links]]
    name = "Notes"
    url = "/#notes"
  [[params.links]]
    name = "Olympiad"
    url = "/#olympiad"
  [[params.links]]
    name = "Projects"
    url = "/#projects"

  # For the "About Me" section
  avatar = "img/profile.jpg"

  olympiad_graphic = "img/olympiad-graphic.svg"